name: Build Docker Image
on: [push]
jobs:
  build_linux:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: actions/checkout@master

      - name: Build Docker image
        run: docker build --build-arg buildType=linux -t lol3r/hentai_bot:latest .

      - name: Login to Repo
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish
        run: docker push lol3r/hentai_bot:latest
