name: Build Docker Image
on: [push]
jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: actions/checkout@master

      - name: Build Docker image
        uses: actions/docker/cli@master
        with:
          args: buildType=linux build -t lol3r/hentai_bot:latest .

      - name: Login to Repo
        uses: actions/docker/login@master

      - name: Publish
        uses: actions/docker/cli@master
        with:
          args: push lol3r/hentai_bot:latest
