name: Build Docker Image
on: [push]
jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: actions/checkout@master

      - name: Build Docker image
        with:
          args: buildType=linux docker build -t lol3r/hentai_bot:latest .

      - name: Login to Repo
        with:
          args: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish
        with:
          args: docker push lol3r/hentai_bot:latest
